baseURL = 'https://tazawa2002.github.io/'
languageCode = 'ja'
langageName = 'Japanese'
defaultContentLanguage = 'ja'
hasCJKLanguage = true
copyright = "Code released under the MIT License (MIT)."
title = 'タザワのブログ'
theme = 'mytheme'
publishDir = 'docs'

[services]
  [services.googleAnalytics]
    ID = 'G-LTLTQKC0D8'

[Auther]
    name = "タザワ"
    bio = "だいがくせい"
    avatar = "images/profile.jpg"



[params]
    text_color = 'dark-gray'
    background_color_class = 'bg-navy'
    auther = 'タザワ'
    email = 'syutotzw@icloud.com'
    favicon = '/images/profile_mini.png'
    site_logo = 'images/profile.png'

[[params.ananke_socials]]
    name = 'Twitter'
    url = 'https://twitter.com/LZ5qFUDUvZeFuHA'
[[params.ananke_socials]]
    name = "GitHub"
    url = "https://github.com/tazawa2002"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = -200
[[menu.main]]
    name = "Articles"
    url = "/post/"
    weight = -180
[[menu.main]]
    name = "LaTeX"
    url = "/latex/"
    weight = -160