name = 'mytheme'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'mytheme'

# The home page of the theme, where the source can be found
homepage = 'https://tazawa2002.github.io/'

# If you have a running demo of the theme
demosite = 'https://tazawa2002.github.io/'

# Taxonomy terms
tags = ['blog', 'company']
features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'tazawa'
  homepage = 'https://tazawa2002.github.io/'
